global:
  image:
    repository: jnj.artifactrepo.jnj.com/argoproj/argocd
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: jnj-artifactory

dex:
  enabled: false

redis:
  image:
    repository: jnj.artifactrepo.jnj.com/redis
    imagePullPolicy: IfNotPresent
