apiVersion: v1
data:
  policy.csv: |
    p, role:read-only, applications, get, */*, allow
    p, role:read-only, clusters, get, *, allow
    p, role:marvel-ro, applications, get, *dce*, allow
    p, role:marvel-ro, clusters, get, *, allow
    p, role:cdr-ro, clusters, get, *, allow
    p, role:cdr-ro, applications, get, *dce*, allow
    g, sa_argocd_ro, role:read-only
    g, sa_argocd_rw, role:admin
    g, argo-account, role:admin
    g, marvel_argocd_ro, role:marvel-ro
    g, cdr_argocd_ro, role:cdr-ro
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"p, role:read-only, applications, get, */*, allow\np, role:read-only, clusters, get, *, allow\np, role:marvel-ro, applications, get, *dce*, allow\np, role:marvel-ro, clusters, get, *, allow\np, role:cdr-ro, clusters, get, *, allow\np, role:cdr-ro, applications, get, *dce*, allow\ng, sa_argocd_ro, role:read-only\ng, sa_argocd_rw, role:admin\ng, argo-account, role:admin\ng, marvel_argocd_ro, role:marvel-ro\ng, cdr_argocd_ro, role:cdr-ro\n","policy.default":"","policy.matchMode":"glob","scopes":"[groups]"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"argocd","meta.helm.sh/release-namespace":"argocd"},"creationTimestamp":"2025-04-10T01:02:32Z","labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd","app.kubernetes.io/version":"v2.10.2","helm.sh/chart":"argo-cd-6.6.0"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"221939229","uid":"5b1a9a77-9115-4980-8e95-9131e89cc12f"}}
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2025-04-10T01:02:32Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.10.2
    helm.sh/chart: argo-cd-6.6.0
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "222262892"
  uid: 5b1a9a77-9115-4980-8e95-9131e89cc12f
